#!/bin/bash
while true; do
    random_wallpaper=$(find $HOME/grive/wallpapers/ubuntu/ -type f -exec file {} \; | awk -F: '{ if ($2 ~/image/) print $1}' | shuf -n 1)
    echo "$random_wallpaper"
    gsettings set org.gnome.desktop.background picture-uri file://$random_wallpaper
    sleep 10m
done &
